from config.gmailConfig import GmailClient
from config.sheetsConfig import slaList, scripts, production
from config.driveConfig import driveClient
import datetime
from config.jsonFiles import DriveFiles

UPLOAD_FILES_ID = DriveFiles["Automation"]["2. Content to Send Off"]
AWAITING_ASSESSMENT_ID = DriveFiles["Automation"]["3. Awaiting Assessment"]
emails = slaList.col_values(1)[1:]
gmailClient = GmailClient()

##Get the script files
currentScripts = scripts.get_all_records()
scriptIds = []
for s in currentScripts: ##Only check the scripts with TBA checked
    if s["Publish"] == "TBA":
        scriptIds.append(s["Id"])

print("requesting")
files = driveClient.list_files_in_folder(UPLOAD_FILES_ID)
noFiles = len(files)
for file in files:
    ##Check the script files
    fileId = file["id"]
    alreadySent = False
    for s in scriptIds: ##Continue to the next iteration only if the spreadsheet has been uploaded
        ##This implies that the team are already aware of the upload.
        if s == fileId:
            alreadySent = True
            break
    if alreadySent:
        continue
    fileName = file["name"]
    driveLink = driveClient.makePublicLink(fileId)
    ##Send email to notify the SLA team that the file has been uploaded
    
    ##Upload Link to the drive
    ##UPDATE THE SCRIPTS DATABASE
    todaysDate = datetime.date.today().strftime("%Y-%m-%d")
    ##Get the script from the production spreadsheet
    scriptCell = production.find(fileId)
    scriptText = ""
    if scriptCell is not None:
        scriptText = production.row_values(scriptCell.row)[1]
    scripts.append_row([todaysDate,"Short Video", "TBA",  driveLink, fileId, "", scriptText])

    ##Move the file to await assessment
    driveClient.move_file(fileId, AWAITING_ASSESSMENT_ID)

##Create the email chain from the list for emails

if noFiles:
    emailChain = ", ".join(emails)
    ##Allow for a singlular or plural language to be used in the email
    if noFiles == 1:
        contentMsg = "<span style='font-weight: bold; color: navy;'>a new piece of content</span> has"
    else:
        contentMsg = f"<span style='font-weight: bold; color: navy;'>{noFiles} pieces of content</span> have"
    html_body = """
            <html>
                <body style=
                    "font-family: Arial, sans-serif; background-color: #f4f6f8; color: #333; padding: 20px;">
                    <table width="100%" style=
                        "max-width: 600px; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 6pxrgba(0,0,0,0.1);"
                    >
                    <tr style="background-color:#006dae;">
                        <td style="padding: 15px; text-align: center;">
                        <img src="https://www.canberra.edu.au/_designs/ucweb/common/images/logo/uc_logo_inline.png" width="160" alt="University of Canberra">
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 25px;">
                        <h2 style="color: #006dae; text-align:center;">🎥 New Content Generated 🎬</h2>
                        <p style="font-size:1.2em;"></p>
                            Hello Everyone <br/>
                            This is an automated message to notify you that {} been added to be assessed. <br/>
                            Check it out and please select <span style="color: green; font-weight: bold;">yes</span>. If you feel this should not be published, then select <span style="color: red; font-weight: bold;">
                            no </span> in the "Publish" column. If you do choose to remove please leave a reason why in the feedback.<br/>
                            </p>
                            <h3 style="color: #006dae; text-align:center;">
                                You can find the new content here 👇
                            </h3>
                            <a style=
                                "display: block; background-color: blue; width: 50%; margin: auto; text-decoration: none; color: white;
                                padding: 5px; font-size: 1.3em; letter-spacing: 0.3em; text-align: center; font-weight: bold; border: 2px solid skyblue;
                                border-radius: 4px;"
                                href="https://docs.google.com/spreadsheets/d/19xR72Spb-X6ncCGhwX1ZvVT0Ia0PIzZ6wSdvwE914i8">
                                Content List
                            </a>
                        <hr style="border:none; border-top:1px solid #ccc; margin:20px 0;">
                        <p style="font-size:14px; color:#666; text-align:center;">
                            <b>Stay connected with UC Wellbeing 🌿</b><br>
                            <i>This message was automatically generated by the UC Wellbeing Automation System.</i>
                        </td>
                    </tr>
                    </table>
                </body>
            </html>
    """.format(contentMsg)
    gmailClient.send_message(emailChain, "New Content Generated for SLA", html_body, True)





    

    




