from config.gmailConfig import gmailClient
from config.sheetsConfig import scripts, slaList
import datetime

###Go through the scripts to check the dates of the updates
records = scripts.get_all_records()
listedDates = []
today = datetime.datetime.now()
dateToCheck = today - datetime.timedelta(days=3)
lateNumber = 0
totalNumber = 0
for record in records:
    if (record["Publish"] == "TBA"):
        listedDate = record["Date Generated"]
        listedDate = listedDate.split("-")
        listedDate = datetime.datetime(int(listedDate[0]), int(listedDate[1]), int(listedDate[2]))
        if listedDate <= dateToCheck:
            lateNumber += 1 ##Check the number of elements that are older than a week
        totalNumber += 1 ##Add up the total number of items on the list

##Check that the item is older than a week and then automatically notify the SLA Team
if True:
    ##Email the team to get them to follow up on the items
    print("Works")
    emails = slaList.col_values(1)[1:]
    emailChain = ", ".join(emails)
    if totalNumber == 1:
        response = "is <span style='color: blue; font-weight: bold;'>1</span> piece of content"
    else:
        response = f"are <span style='color: red; font-weight: bold;'>{totalNumber}</span> pieces of content"
    html_body = """
            <html>
                <body style=
                    "font-family: Arial, sans-serif; background-color: #f4f6f8; color: #333; padding: 20px;">
                    <table width="100%" style=
                        "max-width: 600px; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 6pxrgba(0,0,0,0.1);"
                    >
                    <tr style="background-color:#006dae;">
                        <td style="padding: 15px; text-align: center;">
                        <img src="https://www.canberra.edu.au/_designs/ucweb/common/images/logo/uc_logo_inline.png" width="160" alt="University of Canberra">
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 25px;">
                        <h2 style="color: #006dae; text-align:center;">⚠️ There is Still Content to be Assessed ‼️</h2>
                        <p style="font-size:1.2em;"></p>
                            Hello Team <br/>
                            Just letting you know that there {} yet to be reviewed, please take some time to review it when you can!
                            </p>
                            <h3 style="color: #006dae; text-align:center;">
                                The content list can be found here 👇
                            </h3>
                            <a style=
                                "display: block; background-color: red; width: 50%; margin: auto; text-decoration: none; color: white;
                                padding: 5px; font-size: 1.3em; letter-spacing: 0.3em; text-align: center; font-weight: bold; border: 2px solid skyblue;
                                border-radius: 4px;"
                                href="https://docs.google.com/spreadsheets/d/19xR72Spb-X6ncCGhwX1ZvVT0Ia0PIzZ6wSdvwE914i8">
                                Content List
                            </a>
                        <hr style="border:none; border-top:1px solid #ccc; margin:20px 0;">
                        <p style="font-size:14px; color:#666; text-align:center;">
                            <b>Stay connected with UC Wellbeing 🌿</b><br>
                            <i>This message was automatically generated by the UC Wellbeing Automation System.</i>
                        </td>
                    </tr>
                    </table>
                </body>
            </html>
            """.format(response)
    gmailClient.send_message("harley.drake1996@gmail.com", "There is Content to be Assessed", html_body, True)
    print("Also works")
    

        
