from config.sheetsConfig import published, slaList
from config.gmailConfig import gmailClient
import datetime

##Get the list of items that have been published
allPublished = published.get_all_records()
dateCheck = datetime.date.today() - datetime.timedelta(days=14) ##set the date threshold to be 14 days ago
sentColumn = 11

itemsForNewsletter = [] ##Fetch all items from the previous week (7 days) to display in the newsletter
for item in allPublished:
    status = item["Status"]
    sent = item["Sent To Newsletter"]
    if status != "Uploaded": ##Remove any item that has not yet been uploaded
        continue
    dateStr = item["Date Moved"]
    dateDate = dateStr.split(" ")[0]
    year = int(dateDate.split("-")[0])
    month = int(dateDate.split("-")[1])
    day = int(dateDate.split("-")[2])
    ##Date item to compare
    dateItem = datetime.date(year, month, day)
    if ((dateItem > dateCheck) and (sent == "No")): ##Check that the previous content is from a week ago
        itemsForNewsletter.append(item)

if itemsForNewsletter:
    emails = slaList.col_values(1)[1:]
    emailChain = ", ".join(emails)
    ##Work with all items from the last 14 days
    html_body = """
                <html>
                    <body style=
                        "font-family: Arial, sans-serif; background-color: #f4f6f8; color: #333; padding: 20px;">
                        <table width="100%" style=
                            "max-width: 600px; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 6pxrgba(0,0,0,0.1);"
                        >
                        <tr style="background-color:#006dae;">
                            <td style="padding: 15px; text-align: center;">
                            <img src="https://www.canberra.edu.au/_designs/ucweb/common/images/logo/uc_logo_inline.png" width="160" alt="University of Canberra">
                            </td>
                        </tr>
                        <tr>
                            <td style="padding: 15px; text-align: center;">
                                <h2>HELLO TEAM! 😀</h2>
                                <p>Please find attached, this weeks content, to be shared with the Student Leadership Academy canvas page. Please review each item before publishing to the page.</p>
                                <hr style="border:none; border-top:1px solid #ccc; margin:20px 0;">
                            </td>
                        </tr>
    """
    ##Append content 
    for item in itemsForNewsletter:
        title = item["Title"]
        type = item["Type"]
        if type == "Short Video":
            typeText = "🎥 Short Video"
            typeColour = "#0000FF"
        link = item["Youtube Link"]
        description = item["Description"]
        date = item["Published"].split(" ")[0]
        html_body += f"""
                <tr style="border-bottom: 1px solid black; display: block; margin:auto; width: 95%;">
                    <td style="text-align: center; display: block; margin: auto;">
                    <h3><span
                        style="color: {typeColour}">
                            {typeText}:</span> {title}</h3>
                    <em>Published: <b>{date}</b></em><br>
                    <em>YT Link: <b>{link}</b></em>
                    <p style="text-align: center;">{description}</p>
                    </td>
                </tr>
                """
        ##Update the "Sent to Newsletter" items to Sent
        itemCell = published.find(item["Id"])
        published.update_cell(itemCell.row, 11, "Sent")

    html_body += """
                    <tr>
                        <td>
                        <hr style="border:none; border-top:1px solid #ccc; margin:20px 0;">
                        <p style="font-size:14px; color:#666; text-align:center;">
                            <b>Stay connected with UC Wellbeing 🌿</b><br>
                            <i>This message was automatically generated by the UC Wellbeing Automation System.</i>
                        </td>
                    </tr>
                    </table>
                    </body>
                </html>
    """
    gmailClient.send_message(emailChain, "📰 Newsletter for SLA Canvas Page", html_body, True)


    
